FEATURE: build: Mode tags-from-path lists git tags from a path in the repo

diff --git a/build/check-updates b/build/check-updates
--- a/build/check-updates
+++ b/build/check-updates
@@ -44,11 +44,30 @@ function get-data-json() {
   fi |jq "$expression" |grep -Pio "$pattern"
 }
 
+function get-data-tags-from-path() {
+    local repo=$1; shift
+    local branch=$1; shift
+    local path=$1; shift
+    local tmpdir="/dev/shm/${PROGNAME}/src/${repo//[^[:alnum:]]/_}"
+    local last_hash
+    if [[ -d $tmpdir ]]; then
+        git -C "$tmpdir" fetch origin
+    else
+        mkdir -p "$tmpdir" || return 1
+        git clone "$repo" "$tmpdir" || return 1
+    fi
+    git -C "$tmpdir" checkout "origin/$branch" || return 1
+    last_hash=$(git -C "$tmpdir" log -1 --pretty=format:%H -- connectors/vmware/) || return 1
+    [[ -n $last_hash ]] || return 1
+    git -C "$tmpdir" tag --contains "$last_hash"
+}
+
 function get-data() {
   local method=( ${1//:/$IFS} ) ; shift
   if declare -F -f "$FUNCNAME-$method"; then
     "$FUNCNAME-$method" "$1" "${method[@]:1}" || return 1
   else
+    echo "[ERROR] not implemented: $FUNCNAME-$method" >&2
     return 1
   fi
 }
