FEATURE: build: Implement RPM signing in rpmbuild-docker

diff --git a/build/rpmbuild-docker b/build/rpmbuild-docker
--- a/build/rpmbuild-docker
+++ b/build/rpmbuild-docker
@@ -15,7 +15,7 @@ function usage() {
   echo "Options:"
   sed -nr "s/^[[:space:]]*## ([^:]*): /\1\t/p" -- "$0" |
     while read OPT DESC ; do
-      printf " %-20s %s\n" "$OPT" "$DESC"
+      printf " %-24s %s\n" "$OPT" "$DESC"
     done
   echo
   return 0
@@ -62,6 +62,13 @@ declare SOURCEDIR=$SOURCEDIR
 declare OUTPUTDIR=$OUTPUTDIR
 declare PREBUILDSCRIPT=$PREBUILDSCRIPT
 declare DOWNLOAD=1
+declare SIGN=
+declare GPG_KEYID=
+declare GPG_SECRET_KEY_FILE=
+declare GPG_SECRET_KEY=
+declare GPG_PASSPHRASE_FILE=
+declare GPG_PASSPHRASE_ENV=
+declare GPG_HOMEDIR=${GNUPGHOME:-~/.gnupg}
 declare RPMOPTS=()
 declare RPMBUILDOPTS=()
 declare RPMSPECOPTS=()
@@ -100,6 +107,18 @@ while (( $# > 0 )); do
     --nokeep) NOKEEP=1 ;;
     ## --gitrev: create source0 tarball from git revision
     --gitrev) GITREV=$2 ; shift ;;
+    ## --sign: enable rpm signing
+    --sign) SIGN=1 ;;
+    ## --gpg-homedir: path to gpg homedir
+    --gpg-homedir) GPG_HOMEDIR=$2 ; shift ;;
+    ## --gpg-keyid: gpg keyid for signing
+    --gpg-keyid) GPG_KEYID=$2 ; shift ;;
+    ## --gpg-secret-key-file: armored gpg secret key for signin
+    --gpg-secret-key-file) GPG_SECRET_KEY_FILE=$2 ; shift ;;
+    ## --gpg-passphrase-file: read key passphrase from file
+    --gpg-passphrase-file) GPG_PASSPHRASE_FILE=$2 ; shift ;;
+    ## --gpg-passphrase-env: read key passphrase from environment variable
+    --gpg-passphrase-env) GPG_PASSPHRASE_ENV=$2 ; shift ;;
     # generic args
     --) shift ; break ;;
     -*) usage "Unknown parameter '$1'" && exit 1 ;;
@@ -162,12 +181,48 @@ fi
 [[ ${OUTPUTDIR:0:1} != "/" ]] && OUTPUTDIR=$PWD/$OUTPUTDIR
 [[ -n $REPO && ${REPO:0:1} != "/" ]] && REPO=$PWD/$REPO
 
+if [[ -n $SIGN ]]; then
+  if [[ -n $GPG_PASSPHRASE_FILE ]]; then
+    [[ ${GPG_PASSPHRASE_FILE:0:1} != "/" ]] && GPG_PASSPHRASE_FILE="$PWD/$GPG_PASSPHRASE_FILE"
+    [[ -r $GPG_PASSPHRASE_FILE ]] || fatal 'Cannot not read passphrase file'
+  elif [[ -n $GPG_PASSPHRASE_ENV ]]; then
+    export -n GPG_PASSPHRASE_ENV
+  else
+    echo -n 'Enter sign key passphrase: '
+    { read -rs GPG_PASSPHRASE; ret=$?; echo; ((ret==0)); } || fatal 'Could not read passphrase'
+    GPG_PASSPHRASE_ENV=GPG_PASSPHRASE
+  fi
+  if [[ -n $GPG_SECRET_KEY_FILE ]]; then
+    [[ ${GPG_SECRET_KEY_FILE:0:1} != "/" ]] && GPG_SECRET_KEY_FILE="$PWD/$GPG_SECRET_KEY_FILE"
+    if [[ -z $GPG_KEYID ]]; then
+      GPG_KEYID=$(gpg --show-keys --with-colons "$GPG_SECRET_KEY_FILE" |
+        awk -F : '$1=="sec"{getline;print $10;exit}')
+      [[ -z $GPG_KEYID ]] && fatal 'Cannot read GPG keyid'
+    fi
+  else
+    [[ -d $GPG_HOMEDIR ]] || fatal "GPG homedir $GPG_HOMEDIR not a directory"
+    # select first secret key if none given
+    if [[ -z $GPG_KEYID ]]; then
+      GPG_KEYID=$(gpg --homedir "$GPG_HOMEDIR" --list-secret-keys --with-colons |
+        awk -F : '$1=="sec"{getline;print $10;exit}')
+      [[ -z $GPG_KEYID ]] && fatal 'Cannot guess GPG keyid'
+    fi
+    # export secret key
+    GPG_SECRET_KEY=$(if [[ -n $GPG_PASSPHRASE_FILE ]]; then cat "$GPG_PASSPHRASE_FILE"
+        else (set +x && echo "${!GPG_PASSPHRASE_ENV}"); fi |
+      gpg --homedir "$GPG_HOMEDIR" --batch --passphrase-fd 0 --pinentry-mode loopback \
+        --armor --export-secret-keys --with-fingerprint "$GPG_KEYID") ||
+          fatal 'Failed to export GPG secret key'
+  fi
+fi
+
 echo "SPECFILE: $SPECFILE"
 echo "SPECDIR: $SPECDIR"
 echo "SOURCEDIR: $SOURCEDIR"
 echo "OUTPUTDIR: $OUTPUTDIR"
 echo "PREBUILDSCRIPT: ${PREBUILDSCRIPT:-none}"
 echo "REPO: ${REPO:-none}"
+echo "SIGN: ${SIGN:-0}"
 
 # Yum might take for ages to complete because it CLOEXEC on all available
 # file descriptors and recent dockers sets a very high default limit.
@@ -388,9 +443,11 @@ DOCKER_OPTS=(
   --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/yum"
   --mount "type=bind,src=$CACHEBASE/cache-yum-$DIST,dst=/var/cache/dnf"
   --mount "type=bind,src=$CACHEBASE/cache-shared,dst=/tmp/cache-shared"
-  --mount "type=bind,src=$SOURCEDIR,dst=/tmp/SOURCES"
-  --mount "type=bind,src=$OUTPUTDIR/SRPMS,dst=/tmp/SRPMS"
-  --mount "type=bind,src=$OUTPUTDIR/RPMS,dst=/tmp/RPMS"
+  --mount "type=bind,src=$SOURCEDIR,dst=/tmp/shared/SOURCES"
+  --mount "type=bind,src=$OUTPUTDIR/SRPMS,dst=/tmp/shared/SRPMS"
+  --mount "type=bind,src=$OUTPUTDIR/RPMS,dst=/tmp/shared/RPMS"
+  ${GPG_PASSPHRASE_FILE:+--mount "type=bind,src=$GPG_PASSPHRASE_FILE,dst=/dev/shm/.p,ro"}
+  ${GPG_SECRET_KEY_FILE:+--mount "type=bind,src=$GPG_SECRET_KEY_FILE,dst=/dev/shm/k,ro"}
   ${REPO:+--mount "type=bind,src=$REPO,dst=/tmp/local-repo"}
   ${PREBUILDSCRIPT:+--mount "type=bind,src=$PREBUILDSCRIPT,dst=/tmp/${PREBUILDSCRIPT##*/}"}
 )
@@ -424,8 +481,19 @@ function build_main() {
   trap build_exit EXIT
   OIFS=$IFS
 
-  mkdir -p "$BHOME"
+  mkdir -p -m 700 "$BHOME"
   chown "$BUSER:$BGROUP" "$BHOME"
+
+  if [[ -n $SIGN ]]; then
+    build_runuser mkdir -m 700 /dev/shm/g
+    build_runuser ln -sT /dev/shm/g "$BHOME/.gnupg"
+    build_runuser sh -exc 'GPG_TTY= gpg --passphrase-file /dev/shm/.p \
+      --pinentry-mode loopback --import /dev/shm/k'
+  fi
+
+  mkdir /tmp/build
+  chown "$BUSER:$BGROUP" /tmp/{build,shared}
+  ln -s ../shared/SOURCES /tmp/build/
 
   if [[ -n "$REPO" ]]; then
     cat >/etc/yum.repos.d/local-repo.repo <<'EOF'
@@ -451,7 +519,7 @@ EOF
 
   # Having _topdir /tmp causes problems in el6/el7 because it is not long enough
   # https://access.redhat.com/solutions/1426113
-  RPMOPTS+=(  --define '_topdir /tmp/../tmp/../tmp' )
+  RPMOPTS+=(  --define '_topdir /tmp/../tmp/../tmp/build' )
   rpmbuildopts=( "${RPMOPTS[@]}" "${RPMBUILDOPTS[@]}" )
   rpmspecopts=( "${RPMOPTS[@]}" "${RPMSPECOPTS[@]}" )
 
@@ -470,18 +538,30 @@ EOF
     dlsources=( $(rpmspec -P "/tmp/$SPECFILE" "${rpmspecopts[@]}" |
       sed -nr -e 's,^(source|patch)[0-9]*\s*:\s*(\S+).*,\2,i;T;/:\/\//p') )
     for i in "${dlsources[@]}"; do
-        RUNUSER=1 build_dl "$i" /tmp/SOURCES
+        RUNUSER=1 build_dl "$i" /tmp/shared/SOURCES
     done
   fi
 
   build_runuser rpmbuild "${rpmbuildopts[@]}" -ba "/tmp/$SPECFILE"
 
-  if [[ -n $REPO && -n $UPDATE ]] ; then
-    for repo in RPMS SRPMS; do
-      build_runuser cp -aT "/tmp/$repo/" "/tmp/local-repo/$repo/"
-      build_runuser createrepo --update "/tmp/local-repo/$repo"
-    done
+  if [[ -n $SIGN ]]; then
+    rpm -q rpm-sign || yum install -y rpm-sign
+    rpms=( $(find /tmp/build/{RPMS,SRPMS} -type f -name '*.rpm') )
+    if [[ -n $rpms ]]; then
+      build_runuser sh -exc 'GPG_TTY= rpm \
+        --define "_gpg_sign_cmd_extra_args --passphrase-file /dev/shm/.p --pinentry-mode loopback" \
+        --define "_gpg_name $1" --addsign "${@:2}"' -- "$GPG_KEYID" "${rpms[@]}"
+    fi
   fi
+
+  for repo in RPMS SRPMS; do
+    build_runuser cp -aT "/tmp/build/$repo/" "/tmp/shared/$repo/"
+
+    if [[ -n $REPO && -n $UPDATE ]] ; then
+      build_runuser cp -aT "/tmp/build/$repo/" "/tmp/local-repo/$repo/"
+      build_runuser createrepo --update "/tmp/local-repo/$repo"
+    fi
+  done
 }
 
 # Build RPM in the container
@@ -490,14 +570,16 @@ DOCKER_OPTS+=( --name "$CTNAME" -i --rm )
 trap 'docker kill "$CTNAME"; exit;' INT
 cat <<__EOF__ |docker run "${DOCKER_OPTS[@]}" "$IMAGE" /bin/bash &
 declare -p HOSTNAME
-$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE)
+$(declare -p BGROUP BHOME BUSER DIST DIST_TYPE DIST_VERSION DOWNLOAD KEEP NOKEEP REPO RPMOPTS RPMBUILDOPTS RPMSPECOPTS SPECFILE UPDATE SIGN GPG_KEYID)
+echo "$(getent group "$BGROUP")" >> /etc/group
+echo "$(getent passwd "$BUSER")" >> /etc/passwd
+${GPG_SECRET_KEY:+(umask 0277 && (set +x && echo "${GPG_SECRET_KEY@Q}") > /dev/shm/k && chown "\$BUSER" /dev/shm/k)}
+${GPG_PASSPHRASE_ENV:+(umask 0277 && (set +x && echo "${!GPG_PASSPHRASE_ENV@Q}") > /dev/shm/.p && chown "\$BUSER" /dev/shm/.p)}
 $(printf 'PREBUILDSCRIPT=%q\n' "${PREBUILDSCRIPT##*/}")
 $(declare -f build_exit)
 $(declare -f build_runuser)
 $(declare -f build_dl)
 $(declare -f build_main)
-echo "$(getent group "$BGROUP")" >> /etc/group
-echo "$(getent passwd "$BUSER")" >> /etc/passwd
 # exports for prebuild script
 export -f build_dl build_runuser
 export CACHEDIR=/tmp/cache-shared DIST DIST_TYPE DIST_VERSION
