FEATURE/MINOR: rpmbuild-docker: Allow to override DIST with a custom hook
File ~/.config/rpmbuild-docker/after-image.hook will be sourced, if it
exists, after image setup or checkup.

Example:

$ cat ~/.config/rpmbuild-docker/after-image.hook
if [[ $DIST == centos7* ]]; then
    DIST=el7
fi

if [[ $DIST == centos8* ]]; then
    DIST=el8
fi

if [[ -n $FORCE_DIST ]]; then
    DIST=$FORCE_DIST
fi

diff --git a/rpmbuild/rpmbuild-docker b/rpmbuild/rpmbuild-docker
--- a/rpmbuild/rpmbuild-docker
+++ b/rpmbuild/rpmbuild-docker
@@ -245,6 +245,12 @@ elif [[ -z $DIST ]]; then
   fi
 fi
 
+if [[ -f ~/.config/"${0##*/}/after-image.hook" ]] &&
+   ! source ~/.config/"${0##*/}/after-image.hook"; then
+    echo "FATAL: failed to source after-image.hook" >&2
+    exit 1
+fi
+
 # Extract type and version from $DIST for convenience
 DIST_VERSION=${DIST##*[!0-9]}
 DIST_TYPE=${DIST%$DIST_VERSION}
