MAJOR: zsync: add text file diff feature
With --diff parameter, enable showing differences between text (ASCII) files.

This feature copy text files (maximum 10) to temporary directory on remote host and execute add diff.

diff --git a/zsync/zsync b/zsync/zsync
--- a/zsync/zsync
+++ b/zsync/zsync
@@ -48,6 +48,7 @@ Options:
     -c, --config    Path to configuration file
     -f, --force     Disable dry-run mode
     -H, --host      Set target host
+    -d, --diff      View diff on text files
     -i, --include   Add include rule
     -e, --exclude   Add exclude rule
     -h, --help      Display this help
@@ -124,6 +125,59 @@ function confirm() {
     fi
 }
 
+function show_diff() {
+    local difflist=$1 ; shift
+    local hash action mtime owner file
+    local -a ascii_files=( )
+
+    while read hash acode action mtime perm owner file ; do
+        printf "# %s %s %s %s %s %s\n" \
+               "$acode" "$action" \
+               "$mtime" "$perm" "$owner" "$file"
+        if [[ ${acode:1:2} == "fc"     ]] &&
+           (( ${#ascii_files[@]} <= 10 )) &&
+           [[ $(file $file) =~ ASCII   ]]; then
+            ascii_files+=( "$file" )
+            (( ${#ascii_files[@]} > 10 )) &&
+            warning "Too many text files for diff, display the first 10"
+            continue
+        fi
+    done < $tempfile
+
+    if (( ${#ascii_files[@]} > 0 )); then
+        # echo "ASCII : ${ascii_files[*]}" >&2
+        local tempdir=$(mktemp -d) || fatal "can't create temporary directory"
+        mkdir -p $tempdir/old
+        ln -s / $tempdir/new
+        (
+            IFS=$'\t'
+            function do_remote() {
+                tar zc -C / "${@#/}"
+            }
+            declare -f do_remote
+            echo "do_remote$IFS${ascii_files[*]}"
+        ) |
+            "${SSHCMD[@]}" $i "[[ -x $0 ]] && $SUDO_REMOTE $0 --do-remote || $SUDO_REMOTE bash" |
+            tar zx -C $tempdir/old
+        (
+            cd $tempdir
+            find old -type f -printf "%P\0" |
+                xargs -0 -l -I{} diff --unidirectional-new-file -u old/{} new/{}
+        )
+        rm -rf $tempdir
+    fi
+}
+
+function do_remote() {
+    local IFS=$'\t'
+    while read CMD REST; do
+       [[ $CMD == do_remote ]] && break
+    done
+    [[ $CMD == do_remote ]] || return 1
+    tar zc -C / $REST
+    return $?
+}
+
 function do_rsync() {
     local i retval=0 peer_retval
     local rsync_opts=(
@@ -134,13 +188,13 @@ function do_rsync() {
         --relative
         --omit-dir-times
         --delete
-        --out-format " # %o %M %B %U:%G  /%f"
         --rsync-path "$SUDO_REMOTE rsync"
         -e "${SSHCMD[*]}"
     )
 
-    local dry_run_format=' # %o %M %B %U:%G  /%f'
+    local dry_run_format=' # %i %o %M %B %U:%G  /%f'
     local sync_format=' > %o /%f'
+    local tempfile=$(mktemp)
 
     for i in "${EXCLUDES[@]}"; do
         rsync_opts+=( --exclude "$i" )
@@ -152,7 +206,7 @@ function do_rsync() {
         if [[ -n $HAS_TTY ]]; then
             info "${DRY_RUN:+DRY-RUN }rsync to ${C[blue]}${i}${C[reset]}..."
 
-            rsync "${rsync_opts[@]}" --dry-run --out-format "$dry_run_format" "${INCLUDES[@]}" "$i:/"
+            rsync "${rsync_opts[@]}" --dry-run --out-format "$dry_run_format" "${INCLUDES[@]}" "$i:/" > $tempfile
             peer_retval=$?
 
             if (( peer_retval != 0 )); then
@@ -164,6 +218,12 @@ function do_rsync() {
 
             # bypass if diff empty
             [[ -s $tempfile ]] || continue
+
+            if [[ -n $DIFF ]]; then
+                show_diff $tempfile
+            else
+                cat $tempfile
+            fi
 
             # bypass in dry-run mode
             [[ -n $DRY_RUN ]] && continue
@@ -183,7 +243,7 @@ function do_rsync() {
             retval=1
         fi
     done
-
+    rm -f $tempfile
     return "$retval"
 }
 
@@ -198,9 +258,11 @@ while (( $# > 0 )); do
         -c|--config) CONFIG=$2; shift ;;
         -f|--force) DRY_RUN= ;;
         -R|--become-root) BECOMEROOT=1 ;;
+        -d|--diff) DIFF=1 ;;
         -H|--host) peers+=( "$2" ); shift ;;
         -i|--include) includes+=( "$2" ); shift ;;
         -e|--exclude) excludes+=( "$2" ); shift ;;
+        --do-remote) do_remote; exit $? ;;
         -h|--help) exit_usage ;;
         --) shift; break ;;
         -*) exit_usage 1 ;;
